
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.134:8080/eureka/


spring:
  application:
    name: service-feign
ribbon:
  eureka:
    enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8084

feign:
  hystrix:
    enabled: true